### ISSUE TITLE
Geissystem benannte elemente

### ISSUE THREAD

**Issue by DualL-devel** [FvSS-Fulda/ArduRaCo#1]
Überlegung aus gleissystem.h
Vielleicht sollte man anstatt Vektoren etwas anderes nehmen. Zurzeit würde man die Züge über ihre Nummer aufrufen.
Besonders bei Lichtern und Zügen wäre ein 'string' sinnvoller.
Dann könnte man auch bei den Gleisen die Nummer anstatt eines Pointers verwenden. Das wäre dann vom Benutzer einfacher zu warten.

wäre es nicht sinnvoller (in Anbetracht des begrenzten RAMs) das auf den PI zu verlegen ?

**Comment by Der-Arzt** [comment]
Vielen Dank! Ja, das mit den 'string's als Index habe ich wir vor. Genauer gesagt war das auch schon drin, ist aber mit dem Umzug auf Github verloren gegangen.
Zur Frage mit dem RAM: Eigentlich habe ich vor das ganze - soweit möglich - auf dem Arduino zu lassen, um eine Antikollisionssystem ohne Verzögerung zu ermöglichen. Sollte der Speicherplatz nicht ausreichen werden wir wohl auf den Pi umziehen.

**Comment by Der-Arzt** [comment]
We already did this. Thanks again.
